(ns autoscaler.status)

(def AGENT_STATUS_SLAVE "SLAVE")
(def STATUS_OFFLINE "OFFLINE")
(def AGENT_STATUS_MASTER "MASTER")
(def AGENT_STATUS_DROPPED "DROPPED")

(def STATUS_ONLINE "ONLINE")

(def AGENT_NORMAL_STATUS #{AGENT_STATUS_MASTER AGENT_STATUS_SLAVE})